version: 0.2

phases:

  install:
      commands:
        - echo "Installing Ruby 3.0..."
        - rbenv install 3.2.2
        - rbenv global 3.2.2
        - ruby -v

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - rbenv global 3.2.2 # Configura la versión de Ruby
      - gem install bundler
      - bundle install 
  build:
    commands:
      - echo "Running tests..."
      - bundle exec rake test

  post_build:
    commands:
      - echo "Building artifacts..."
      # Aquí puedes realizar cualquier acción adicional, como la creación de artefactos o la preparación de archivos para despliegue.

artifacts:
  files:
    - '**/*'  # Incluye todos los archivos en el resultado final, ajusta esto según tus necesidades.


