version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - bundle install --deployment

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 3.0

    commands:
      - echo "Running tests..."
      - bundle exec rake test

  post_build:
    commands:
      - echo "Building artifacts..."
      # Aquí puedes realizar cualquier acción adicional, como la creación de artefactos o la preparación de archivos para despliegue.

artifacts:
  files:
    - '**/*'  # Incluye todos los archivos en el resultado final, ajusta esto según tus necesidades.
