name: CI/CD Pipeline
on:
  push:
    branches:
      - master
phases:
  install:
    runtime-versions:
      ruby: 3.0  # Reemplaza con la versión de Ruby que estás usando
  pre_build:
    commands:
      - gem install bundler
      - bundle install
      - echo "Installing dependencies"
      - bundle install --path vendor/bundle
  build:
    commands:
      - echo "Building the application"
  post_build:
    commands:
      - echo "Post build steps"
artifacts:
  files: '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: |
          bundle exec rake test